version: "3.7"
services:
    api:
        hostname: api.local.com
        build:
            args:
                user: www-data
                uid: 1000
            context: ./
            dockerfile: ./api/Dockerfile
        image: api
        container_name: api
        restart: unless-stopped
        working_dir: /var/www/html/api
        volumes:
            - /var/log/laravel/jump_park:/var/www/html/api/storage
            - /tmp:/tmp/
        networks:
            - network
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: 250M
                reservations:
                    cpus: '0.25'
                    memory: 250M
        extra_hosts:
            - "host.docker.internal:host-gateway"
        links:
            - redis

    nginx:
        image: nginx:1.20-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./api:/var/www/html/api
            - ./conf/nginx/api.conf:/etc/nginx/conf.d/api.conf
        networks:
            - network

    redis:
        image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
        container_name: redis
        ulimits:
            memlock: -1
        ports:
            - "6379:6379"
        volumes:
            - dragonflydata:/tmp:rw
        networks:
            - network

    keycloak:
        hostname: keycloak.local
        image: jboss/keycloak:16.1.1
        container_name: keycloak
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            DB_VENDOR: MYSQL
            DB_ADDR: 192.168.10.25
            DB_DATABASE: keycloak
            DB_SCHEMA: keycloak
            DB_USER: keycloak
            DB_PASSWORD: k&ycl0ak
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
#        command:
#            - start-dev
        networks:
            - network

networks:
    network:
      driver: bridge
volumes:
    dragonflydata:

